workflows:
  ios-test-release:
    name: iOS TestFlight Gallery Test
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic API Key
    environment:
      groups:
        - appstore_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # DİKKAT: Eğer yepyeni bir test uygulaması açtıysan buraya onun Bundle ID'sini yaz.
        # Ana uygulamanın üzerine atacaksan com.kgs.kgsyksDestek olarak bırakabilirsin.
        BUNDLE_ID: "com.kgs.kgsyksDestek"
    scripts:
      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Configure Xcode signing
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Podfile.lock
          rm -rf Pods
          rm -rf .symlinks
          flutter precache --ios
          pod install --repo-update
      - name: Build iOS app ipa for release
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive/dSYMs
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
